keys:
  evmPrivateEncrypted: A3_ALEuhyNzvhgu7oH0qCyG59WTsP7NCmOGZ651cd0FKRl8Zd1bQMsciJU0WAXhAAQaWUGUArDygtwrTDF_VF_peS6Sqgv-j1f5doUeZUdAMsp9qddd4eggFR0pMbAtFOjf2FM5Ckwz2bztzJYDnrg

features:
  assistivePricing: true
  newContributorGreeting:
    enabled: true
  publicAccessControl:
    setLabel: false
    fundExternalClosedIssue: false

payments:
  evmNetworkId: 100
  basePriceMultiplier: 2
  issueCreatorMultiplier: 3
  maxPermitPrice: 1000

timers:
  reviewDelayTolerance: 30 days
  taskStaleTimeoutDuration: 30 days
  taskFollowUpDuration: 3.5 days
  taskDisqualifyDuration: 7 days

miscellaneous:
  promotionComment: "<h6>If you've enjoyed your experience in the DevPool, we'd appreciate your support. Follow <a href='https://github.com/ubiquity'>Ubiquity on GitHub</a> and star <a href='https://github.com/ubiquity/devpool-directory'>this repo</a>. Your endorsement means the world to us and helps us grow!</h6><h6>We are excited to announce that the DevPool and UbiquiBot are now available to partners! Our ideal collaborators are globally distributed crypto-native organizations, who actively work on open source on GitHub, and excel in research & development. If you can introduce us to the repository maintainers in these types of companies, we have a special bonus in store for you!</h6>"
  maxConcurrentTasks: 2
  registerWalletWithVerification: false

disabledCommands: []

incentives:
  comment:
    elements:
      blockquote: 0
    totals:
      word: 0

labels:
  time:
    - "Time: <1 Hour"
    - "Time: <2 Hours"
    - "Time: <4 Hours"
    - "Time: <1 Day"
    - "Time: <1 Week"
  priority:
    - "Priority: 1 (Normal)"
    - "Priority: 2 (Medium)"
    - "Priority: 3 (High)"
    - "Priority: 4 (Urgent)"
    - "Priority: 5 (Emergency)"
